version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: saturday
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
    ignore:
      - dependency-name: 'eslint'
      - dependency-name: '@actions/github'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: saturday
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
